# Generated by Django 5.0.1 on 2024-01-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={},
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterOrderWithRespectTo(
            name="task",
            order_with_respect_to="user",
        ),
    ]
